server:
  port: 80
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform : postgres
    url: jdbc:postgresql://localhost:5433/dofustuff?currentSchema=sch_dofustuff
    username: dofustuff
    password: "DofusStuff01*"
    driverClassName: org.postgresql.Driver
graphql:
  host: "https://nexus-factory.ovh"
  port: ":9080"
  path: "/auth"